### ISSUE TITLE
Infinite boardsize?

### ISSUE THREAD

**Issue by euank** [drusepth/mmorpgrps#2]
The existing implementation talks about the boardsize being infinite. That means if knights move randomly over time, they'll tend to end up in very boring states of all knights being in the middle of nowhere.

I think that gameplay can be improved by either having a tendency for the board to not explode in size, or at least to have a limiting factor on the gameboard size (e.g. width/height could be the total number of souls \* some_constant).

However, I haven't thought about this enough to claim with confidence that this will definitely be an improvement; worth thinking about though!

**Comment by drusepth** [comment]
I think board size as a function of knight population may be a good compromise between scale and excitement, allowing the world to expand as more and more players join without needing any adjustments for small populations either.

I think it'd be best to implement this with just a scaling knight-to-world-side-length coefficient that lets us get it in and adjust density from a constant.

Now to just find the time.

**Comment by drusepth** [comment]
Worlds now have static heights and widths that can be manipulated up/down as needed, and movement within the world now wraps around the borders (as if the world were round).
